apiproject/apiproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('ranuser.urls')),
    path('admin/', admin.site.urls),
]

apiproject/ranuser/urls.py
from django.urls import path

from . import views

app_name = 'myapp'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('users', views.UserView,name= 'user'),
    path('list', views.UserListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/',views.UserDeleteView.as_view(), name='delete'),
]

apiproject/ranuser/models.py
from django.db import models

# Create your models here.
class UserData(models.Model):
    name = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    image = models.ImageField(upload_to = 'media')

    

apiproject/ranuser/views.py
from django.shortcuts import render
import requests
from django.views.generic import TemplateView, ListView,DetailView, CreateView, UpdateView, DeleteView, View
from ranuser.models import UserData
from django.urls import reverse_lazy
from django.shortcuts import redirect





class HomeView(TemplateView):
    template_name = "home.html"


# class UserView(CreateView):
def UserView(request):

    response = requests.get('https://randomuser.me/api')
    data = response.json()

    # for i in data['results'][1]['name']:
    #     print(i)
    title = data['results'][0]['name']['title']
    first = data['results'][0]['name']['first']
    last = data['results'][0]['name']['last']


    final_name = " ".join([first,last])

    #############################################
    final_name = ". ".join([title, final_name])          #Final name of the user
    # print(final_name)

    #############################################
    agee = data['results'][0]['dob']['age']               # age of the user
    # print(dob)


    ############################################
    gender = data['results'][0]['gender']                   #Gender
    # print(gender)


    street1 = str(data['results'][0]['location']['street']['number'])
    street2 = str(data['results'][0]['location']['street']['name'])
    city = data['results'][0]['location']['city']
    state = data['results'][0]['location']['state']
    postcode = str(data['results'][0]['location']['postcode'])



    ###############################################
    address = ", ".join([street1,street2, city, state, postcode])  # Final address
    # print(address)


    ###############################################
    email = data['results'][0]['email']                       #Email field
    # print(email)


    ##################################################
    image = data['results'][0]['picture']['medium']            #Image
    # print(image)

    model = UserData

    context_object_name = 'use_data'

    # user_data = {'name': final_name, 'age': agee, 'gender':gender, 'address':address, 'email':email, 'image':image}

    user = UserData.objects.create( name = final_name, age= agee, gender = gender, address=address, email=email, image=image)
    user.save()

    # return render(request,'user_list.html',)

    return redirect('myapp:detail', pk=user.pk)





class UserListView(ListView):
    model = UserData
    context_object_name = 'user_list'
    template_name = 'user_list.html'





class UserDetailView(DetailView):
    model = UserData
    context_object_name = 'user_detail'
    template_name = 'user_detail.html'


class UserDeleteView(DeleteView):
    model = UserData
    context_object_name = 'delete_user'
    template_name = 'user_delete.html'
    success_url = reverse_lazy('myapp:list')

apiproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "master.css" %}">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

      <a class="navbar-brand" href="#">MyAPP</a>

      <!-- <img src="{% static "download.png" %}" width="30" height="30" alt=""> -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:list'%}">List <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>

          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
      </div>

    </nav>
    <br>
    <br>

{% block content %}
   {% endblock %}

  </body>
</html>

apiproject/templates/home.html
<!-- {% extends "base.html" %}
{% load static %}

{% block content %}

<h1>Hello</h1>
{% endblock %} -->
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Hello</h1>
  </body>
</html>

apiproject/templates/user_delete.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="{% static "master.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="container">
       <form class="deletee" method="post">
         {% csrf_token %}
         <p>Are you sure you want to delete "{{ delete_user.name }}"?</p>
         <input type="submit" class="btn btn-danger"  value="Delete">
         <a href="{% url 'myapp:detail' pk=delete_user.pk %}"><button type="button" class="btn btn-warning">Back</button></a>
         
       </form>
    </div>
  </body>
</html>

apiproject/templates/user_detail.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
  <div class="jumbotron">
    <ul>
      <li><h5>Name : {{  user_detail.name}}</h5></li>
      <li><h5>Gender :  {{user_detail.gender}}</h5></li>
      <li><h5>Age : {{user_detail.age}}</h5></li>
      <li><h5>Email : {{user_detail.email}}</h5></li>
      <li><a href="{{user_detail.image}}"><h5>Image : {{user_detail.image}}</h5></a></li>
      <br>
      <br>
      <a href="{% url 'myapp:list' %}"><button type="button" class="btn btn-warning">Back</button></a>

      <a href="{% url 'myapp:delete' pk=user_detail.pk %}">delete</a>
    </ul>
  </div>
</div>

{% endblock %}

apiproject/templates/user_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}



{% block content %}
<div class="list_main">
  <div class="container">

{% if user_list %}
{% for user in user_list %}

<ul>
 <li><a href="{% url 'myapp:detail' pk=user.pk %}">
   <div class="jumbotron">
     <h4 class="list_content">{{user.name}}</h4>
   </div>
 </a></li>
</ul>

{% endfor %}

{% else %}
<div class="jumbotron">
  <h1>! No User Present ! Click on add button to add user</h1>
</div>
{% endif %}

<div class="container">
  <div class="container">
    <div class="container">
        <p><a type="button" class="btn btn-primary" href="{% url 'myapp:user' %}">Add</a></p>
    </div>
  </div>
</div>


  </div>
</div>
{% endblock %}